[WIP] Add adminer
kurtosis-tech/ethereum-package pull request #295
Opened 2023-10-16 17:49 UTC by bharath-123

2023-10-20 08:12 UTC, Makpara approved these changes

2023-10-23 10:40 UTC, h4ck3rk3y requested changes

2023-10-23 10:40 UTC, h4ck3rk3y commented on src/mev_relay/mev_relay_launcher.star
> +<<<<<<< HEAD
there's a merge conflict here!!

2023-10-26 07:48 UTC, bharath-123 commented on src/mev_relay/mev_relay_launcher.star
> +<<<<<<< HEAD
fixed!

2023-10-30 11:00 UTC, h4ck3rk3y requested changes

2023-10-30 11:00 UTC, h4ck3rk3y commented on src/mev_relay/mev_relay_launcher.star
> +postgres_module = import_module("github.com/bharath-123/postgres-package/main.star@add-adminer")
can you fix this?

2023-10-31 06:46 UTC, bharath-123 commented
hey this is fixed!

2023-10-31 12:01 UTC, h4ck3rk3y approved these changes

2023-11-01 10:15 UTC, h4ck3rk3y requested changes

2023-11-01 10:15 UTC, h4ck3rk3y commented on src/mev_relay/mev_relay_launcher.star
> -        persistent=DONT_PERSIST_TO_DISK,
why are you removing this?

2023-11-01 10:15 UTC, h4ck3rk3y commented on src/mev_relay/mev_relay_launcher.star
> +        launch_adminer=True,
can you take the `True` out as a constant?

2023-11-01 10:19 UTC, h4ck3rk3y approved these changes

2023-11-01 11:45 UTC, merged